name = "S - Gradient Cloud" 
description = "A cloud of pulsing circles gradually cycles through colors ; switch between gradient color ranges and control placement of cloud"
knob1 = "X position"
knob2 = "Y Position"
knob3 = "Cloud pattern and swell" 
knob4 = "Gradient select"
released = "March 18 2019"
