name = "S - Tall Towers-Trails" 
description = "Stacked Rectangle Scope with History Fade"
knob1 = "Line Start Point X"
knob2 = "Line Start Point Y"
knob3 = "History Opacity" 
knob4 = "Color"
released = "September 7 2017"
