name = "S - Sound Jaws-Trails" 
description = "Oscilloscope teeth with history fade and tooth color cycle"
knob1 = "Number of Teeth"
knob2 = "Tooth Shape"
knob3 = "History Opacity" 
knob4 = "Colorshift Speed"
released = "September 7 2017"
