name = "S - Sound Jaws-Image-Trails" 
description = "Oscilloscope teeth with background image cycle, tooth color cycle, history fade"
knob1 = "Number of Teeth"
knob2 = "Tooth Shape"
knob3 = "History Opacity" 
knob4 = "Colorshift Speed"
released = "September 7 2017"
