name = "S - Floating Ball-Trails" 
description = "Circle radius tracks amplitude, falls on trigger and drifts L-R with history fade"
knob1 = "Drift Speed L-R"
knob2 = "Rise Speed"
knob3 = "History Opacity" 
knob4 = "Color"
released = "September 7 2017"
