name = "S - Perspective Lines LFO" 
description = "Oscilloscope Composed of a Row of Circles, Each Connected to a Vanishing Point; Vanishing Point Movements Controlled by Two LFOs"
knob1 = "Line Origin Point Horizontal Movement LFO Rate"
knob2 = "Line Origin Point Veritcal Movement LFO Rate"
knob3 = "Thickness" 
knob4 = "Color"
released = "November 15, 2018"