name = "T - Draws Hashmarks-Trails" 
description = "Audio trigger draws vertical hashmarks on horizontal ruled background with history fade"
knob1 = "Zoom"
knob2 = "Hash Density"
knob3 = "Trails Fade" 
knob4 = "Color"
released = "September 25 2017"
