name = "T - Image Shadow Grid" 
description = "Audio-Triggered Image Cycle in a 2x2 grid with drop shadow"
knob1 = "Image Scale"
knob2 = "Slide"
knob3 = "Flip" 
knob4 = "Shadow Distance"
released = "September 7 2017"