name = "T - Image + Square" 
description = "Random Image Placement with Square Border"
knob1 = "Image Size"
knob2 = "Square Size"
knob3 = "Image Opacity" 
knob4 = "Square Color"
released = "July 28 2017"