name = "S - Sound Jaws-Image" 
description = "Oscilloscope teeth with background image cycle and tooth color cycle"
knob1 = "Clench"
knob2 = "Number of Teeth"
knob3 = "Tooth Shape" 
knob4 = "Colorshift Speed"
released = "September 7 2017"
