name = "T - Slideshow Grid-AG-Alpha" 
description = "Images placed randomly in four quadrants on trigger with recursive screen feedback and opacity control"
knob1 = "Recursive Screen Scale X"
knob2 = "Recursive Screen Scale Y"
knob3 = "Recursive Screen Opacity" 
knob4 = "Recursive Screen Flip"
released = "September 7 2017"
