name = "S - Grid Slide Square" 
description = "Grid of oscillating squares with LFO-controlled sliding rows and animated color fade"
knob1 = "Slide LFO speed"
knob2 = "Slide LFO range"
knob3 = "Size" 
knob4 = "Color Selector"
released = "March 18 2019"
