name = "S - Circle Row - LFO" 
description = "Sound amplitude controls diameter of circles with LFO controlling row position"
knob1 = "Number of Circles"
knob2 = "Diameter"
knob3 = "Y Position LFO rate" 
knob4 = "Color"
released = "October 1 2018"
