name = "S - Simple - LFO" 
description = "Simple oscilloscope mode with history fade and LFO controlling line width."
knob1 = "Line Width LFO rate"
knob2 = "Y Position"
knob3 = "Trails Fade"
knob4 = "Color"
released = "October 1 2018"
