name = "S - X Scope-Trails" 
description = "X line-oscilloscope with history fade"
knob1 = "Line Width"
knob2 = "Shadow Distance"
knob3 = "History Opacity" 
knob4 = "Color"
released = "September 7 2017"
