name = "T - BoM OG Trans" 
description = "Circle placed randomly on trigger with recursive feedback screen"
knob1 = "Ball size"
knob2 = "Feedback screen size"
knob3 = "Feedback screen transparency" 
knob4 = "Ball color; grayscale/color"
released = "January 10 2019"