name = "T - Img Spin Grid LFO" 
description = "Audio-Triggered Image Cycle in a 2x2 grid with spin animated by LFO"
knob1 = "Image Scale"
knob2 = "Slide"
knob3 = "Distance From Center" 
knob4 = "Spin Speed"
released = "October 31 2018"