name = "T - Slideshow Big Center-AG-Trails" 
description = "Random image displayed on trigger with superimposed recursive screen feedback and history fade"
knob1 = "Recursive Screen Position X"
knob2 = "Recursive Screen Position Y"
knob3 = "History Opacity" 
knob4 = "Recursive Screen Scale"
released = "September 7 2017"
