name = "T - Rotation Grid-Trails" 
description = "Audio trigger rotates 3 independent grids with history fade"
knob1 = "Line Length and Width"
knob2 = "Rotation Direction and Speed"
knob3 = "Trails Fade" 
knob4 = "Color"
released = "September 25 2017"
