name = "T - Bits H + Image" 
description = "Horizontal Bits with Background Image"
knob1 = "Bits Amount"
knob2 = "Bits Length"
knob3 = "Image Cycle Rate" 
knob4 = "Bits Color"
released = "July 28 2017"