name = "S - V Line Traveller-Trails" 
description = "Scrolling vertical line tracks audio amplitude with history fade"
knob1 = "Line Width"
knob2 = "Travel Direction and Speed"
knob3 = "Trails Fade" 
knob4 = "Color"
released = "September 25 2017"
