name = "S - Gradient Vortex" 
description = "A column of circles gradually cycles through colors; adjust color shift and pattern independently; select from 4 gradient/pattern categories"
knob1 = "Blue channel change rate"
knob2 = "Green channel change rate"
knob3 = "Red channel change rate" 
knob4 = "Gradient select"
released = "March 18 2019"
