name = "S - Slinky Text" 
description = "Offset text layers bounce with audio input; offset angle controlled by LFO."
knob1 = "LFO rate"
knob2 = "Size"
knob3 = "Veil trans" 
knob4 = "Color selector"
released = "March 18 2019"
