name = "S - Mirror Grid-Trails" 
description = "Grid with oscilloscoping vertical lines plus history fade"
knob1 = "Line Width"
knob2 = "Line Spacing"
knob3 = "Trails Fade" 
knob4 = "Color"
released = "September 25 2017"
