name = "T - Marching Four - Img" 
description = "Four images travel across screen at different speeds on audio trigger"
knob1 = "X speed"
knob2 = "Y speed"
knob3 = "Image width" 
knob4 = "Image height"
released = "August 23 2018"