name = "S - Simple Oscilloscope-Trails" 
description = "Simple oscilloscope mode with history fade"
knob1 = "Line Width"
knob2 = "Y Position"
knob3 = "Trails Fade"
knob4 = "Color"
released = "September 25 2017"
