name = "S - Two Scopes-Trails" 
description = "Two vertical line-oscilloscopes with history fade"
knob1 = "X Position"
knob2 = "Line Width"
knob3 = "History Opacity" 
knob4 = "Color"
released = "September 7 2017"
